![license_header_logo](../../../images/license_header_logo.png)

> **Copyright (c) 2021 CertifAI Sdn. Bhd.**<br>
<br>
This program is part of OSRFramework. You can redistribute it and/or modify
<br>it under the terms of the GNU Affero General Public License as published by
<br>the Free Software Foundation, either version 3 of the License, or
<br>(at your option) any later version.
<br>
<br>This program is distributed in the hope that it will be useful
<br>but WITHOUT ANY WARRANTY; without even the implied warranty of
<br>MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
<br>GNU Affero General Public License for more details.
<br>
<br>You should have received a copy of the GNU Affero General Public License
<br>along with this program.  If not, see <http://www.gnu.org/licenses/>.
<br>

# Introduction

Maps allow us to transform data in a DataFrame or Series one value at a time for an entire column. However, often we want to group our data, and then do something specific to the group the data is in. 

As you'll learn, we do this with the `groupby()` operation.  We'll also cover some additional topics, such as more complex ways to index your DataFrames, along with how to sort your data.

# Notebook Content

* [Groupwise Analysis](#Groupwise-analysis)


* [Sorting](#Sorting)

# Groupwise analysis

One function we've been using heavily thus far is the `value_counts()` function. We can replicate what `value_counts()` does by doing the following:

In [1]:
import pandas as pd

games = pd.read_csv("../../../resources/day_01/twitch_game_data.csv", index_col=0)

In [2]:
games

,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
Rank,,,,,,,,,,,
1,League of Legends,1,2016,94377226,1362044 hours,530270,2903,129172,127021,1833,69.29
2,Counter-Strike: Global Offensive,1,2016,47832863,830105 hours,372654,2197,120849,64378,1117,57.62
3,Dota 2,1,2016,45185893,433397 hours,315083,1100,44074,60815,583,104.26
4,Hearthstone,1,2016,39936159,235903 hours,131357,517,36170,53749,317,169.29
5,Call of Duty: Black Ops III,1,2016,16153057,1151578 hours,71639,3620,214054,21740,1549,14.03
...,...,...,...,...,...,...,...,...,...,...,...
196,War Thunder,6,2021,704459,73613 hours,8812,223,7035,979,102,9.57
197,Muck,6,2021,701456,31741 hours,60091,112,8591,975,44,22.10
198,Trials Rising,6,2021,698899,4626 hours,217333,26,581,972,6,151.08
199,Little Nightmares II,6,2021,695130,27581 hours,43518,105,6128,966,38,25.20
200,Tabletop RPGs,6,2021,688130,23602 hours,20018,122,2567,957,32,29.16

In [3]:
games.groupby('Game').Game.count().sort_values(ascending=False)

Game
Dungeons & Dragons                           67
RuneScape                                    66
Warcraft III                                 66
Heroes of the Storm                          66
The Elder Scrolls V: Skyrim                  66
                                             ..
DreadOut 2                                    1
Pok<U+00E9>mon Trading Card Game Online       1
Dragon Quest XI: Echoes of an Elusive Age     1
Pok<U+00E9>mon Unite                          1
.hack//G.U. Last Recode                       1
Name: Game, Length: 1676, dtype: int64

`groupby()` created a group of games according to their names. Then, for each of these groups, we grabbed the `Game` column and counted how many times it appeared.  `value_counts()` is just a shortcut to this `groupby()` operation. 

We can use any of the summary functions we've used before with this data. For example, to get the highest average viewer ratio based on Game type, we can do the following:

In [4]:
games.groupby('Game').Avg_viewer_ratio.max().sort_values(ascending=False)

Game
Twitch Presents                                  13601.87
Sparkster                                        11457.47
Home Run Derby VR                                10783.08
RNC 2016                                          9439.39
Brain Age: Train Your Brain in Minutes a Day!     9105.84
                                                   ...
Skyforge                                             4.85
Call Of Duty: Modern Warfare                         4.43
.hack//G.U. Last Recode                              4.12
Battlefield Hardline                                 3.88
World of Warcraft: Battle for Azeroth                3.53
Name: Avg_viewer_ratio, Length: 1676, dtype: float64

You can think of each group we generate as being a slice of our DataFrame containing only data with values that match. This DataFrame is accessible to us directly using the `apply()` method, and we can then manipulate the data in any way we see fit. For example, here's one way of selecting average viewer for each game in the dataset:

In [5]:
games.groupby('Game').apply(lambda df: df.loc[:, "Avg_viewers"])

Game                         Rank
.hack//G.U. Last Recode      199      202
60 Parsecs!                  109      736
60 Seconds!                  126      361
                             54      1040
                             199      152
                                     ...
theHunter: Call of the Wild  125      413
                             142      383
                             163      302
                             163      461
                             196      434
Name: Avg_viewers, Length: 13199, dtype: int64

For even more fine-grained control, you can also group by more than one column. For an example, here's how we would pick out the best game by game _name_, _month_ and _year_:

In [6]:
games.groupby(['Game', 'Month' ,'Year']).apply(lambda df: df.loc[df.Avg_viewer_ratio.idxmax()])

                                                               Game  Month  \
Game                        Month Year
.hack//G.U. Last Recode     11    2017      .hack//G.U. Last Recode     11
60 Parsecs!                 9     2018                  60 Parsecs!      9
60 Seconds!                 3     2017                  60 Seconds!      3
                            7     2016                  60 Seconds!      7
                                  2019                  60 Seconds!      7
...                                                             ...    ...
theHunter: Call of the Wild 6     2019  theHunter: Call of the Wild      6
                            7     2018  theHunter: Call of the Wild      7
                            10    2017  theHunter: Call of the Wild     10
                            11    2017  theHunter: Call of the Wild     11
                            12    2017  theHunter: Call of the Wild     12

                                        Year  Hours_watched Hours_Streamed  \
Game                        Month Year
.hack//G.U. Last Recode     11    2017  2017         145350    35258 hours
60 Parsecs!                 9     2018  2018         529688     1867 hours
60 Seconds!                 3     2017  2017         263482      679 hours
                            7     2016  2016         268754      597 hours
                                  2019  2019         435311     1188 hours
...                                      ...            ...            ...
theHunter: Call of the Wild 6     2019  2019         312124    16140 hours
                            7     2018  2018         342667     8633 hours
                            10    2017  2017         307138    11226 hours
                            11    2017  2017         275393     9241 hours
                            12    2017  2017         224528    11504 hours

                                        Peak_viewers  Peak_channels  \
Game                        Month Year
.hack//G.U. Last Recode     11    2017          1222            258
60 Parsecs!                 9     2018         31960             27
60 Seconds!                 3     2017         31311             10
                            7     2016         32505             10
                                  2019         41049             13
...                                              ...            ...
theHunter: Call of the Wild 6     2019         13252             69
                            7     2018         27600             28
                            10    2017         36876             63
                            11    2017         13279             41
                            12    2017          5978             40

                                        Streamers  Avg_viewers  Avg_channels  \
Game                        Month Year
.hack//G.U. Last Recode     11    2017       3174          202            49
60 Parsecs!                 9     2018        606          736             2
60 Seconds!                 3     2017        240          354             0
                            7     2016        275          361             0
                                  2019        630          585             1
...                                           ...          ...           ...
theHunter: Call of the Wild 6     2019       2602          434            22
                            7     2018       1851          461            11
                            10    2017       2232          413            15
                            11    2017       1312          383            12
                            12    2017       1474          302            15

                                        Avg_viewer_ratio
Game                        Month Year
.hack//G.U. Last Recode     11    2017              4.12
60 Parsecs!                 9     2018            283.71
60 Seconds!                 3     2017            388.04
                            7     2016            450.17
                                  2019            366.42
...                                                  ...
theHunter: Call of the Wild 6     2019             19.34
                            7     2018             39.69
                            10    2017             27.36
                            11    2017             29.80
                            12    2017             19.52

[13195 rows x 11 columns]

Another `groupby()` method worth mentioning is `agg()`, which lets you run a bunch of different functions on your DataFrame simultaneously. For example, we can generate a simple statistical summary of the dataset as follows:

In [7]:
games.groupby(['Game']).Avg_viewers.agg([len, min, max])

                             len  min   max
Game
.hack//G.U. Last Recode        1  202   202
60 Parsecs!                    1  736   736
60 Seconds!                    9  152  1040
7 Days to Die                 66  133  3219
<U+014C>kami                   1  244   244
...                          ...  ...   ...
osu!                          66  587  3335
rFactor 2                      1  897   897
skribbl.io                     7  440  1483
some some convenience store    1  461   461
theHunter: Call of the Wild    9  204   586

[1676 rows x 3 columns]

Effective use of `groupby()` will allow you to do lots of really powerful things with your dataset.

# Sorting

### pandas.DataFrame.sort_values
Sort by the values along either axis.

In [8]:
games.sort_values(by="Streamers", ascending=False)

,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
Rank,,,,,,,,,,,
1,Fortnite,12,2018,118143183,9027163 hours,418403,22408,1013029,159008,12149,13.09
1,Fortnite,1,2019,126502656,10205058 hours,649136,56274,1013016,170259,13734,12.40
1,Fortnite,8,2018,131436549,8166820 hours,687062,17450,974227,176899,10991,16.09
1,Fortnite,7,2018,152086231,8073931 hours,827125,19495,945248,204692,10866,18.84
1,Fortnite,5,2018,144602326,7645739 hours,576926,18000,930299,194619,10290,18.91
...,...,...,...,...,...,...,...,...,...,...,...
140,Star Wars Battlefront,6,2016,150868,35150 hours,3004,164,0,209,48,4.29
115,Star Wars Battlefront,4,2016,216470,45101 hours,35256,155,0,301,62,4.80
125,Star Wars Battlefront,5,2016,176777,38830 hours,2119,189,0,237,52,4.55
157,Star Wars Battlefront,9,2016,129753,26612 hours,2044,133,0,180,37,4.88
31,IRL,12,2016,2376035,22508 hours,38017,195,0,3197,30,105.56

# Contributors

**Author**
<br>Chee Lam

# References

1. [Learning Pandas](https://www.kaggle.com/learn/pandas)
2. [Pandas Documentation](https://pandas.pydata.org/docs/reference/index.html)